routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Models\Items;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('users', [UserController::class, 'index'])->name('users.index');
Route::resource('users', 'UsersController')->only([ 'index', 'store', 'create']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Category extends Model
{
    use HasFactory;
    use softDeletes;
}

app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;


class Item extends Model
{
    use HasFactory;
    use softDeletes;
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class User extends Model
{
    use HasFactory, softDeletes;
    protected $perPage = 20;
    protected $fillable = ['mail_address','password', 'name', 'address', 'phone'];
    /**
     * Get all Users .
     *
     * @return oject $data
     */
    public function getUsers ()
    {
        return $data = user::orderBy('mail_address')->paginate();
    }

     /**
     * create Users .
     * @param oject $request
     * @return oject session()
     */
    public function createUser($request)
    {   
        $input = $request->validated();
        $input['password'] = bcrypt($input['password']);
        $add = user::create($input);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class UserController extends Controller
{
    /**
     * function index().
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('user.list');
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CreateUserRequest;
use App\Models\User;

class UsersController extends Controller
{   
    public $user;

    /**
     * create construct oject 
     */
    public function __construct(User $user)
    {
        $this->user = $user;
    }  
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {   
        $data = $this->user->getUsers(); 
        return view('user.listusers', ['data' => $data]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  pp\Http\Requests\CreateUserRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {   
        $this->user->createUser($request);
        session()->flash('message', 'Thêm mới người dùng thành công');
        return redirect()->route('users.index');
    }
}

resources/views/home.blade.php
<html> 
<header>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<title>@yield('title')</title>
<style type="text/css">
    #header{
        background-color:#39e4c2;
        text-align:center;
        padding:5px 0px;
        font-size: 17pt;
        height: 120px;
    }
    #content{
        padding:10px 20px;
        height:  calc(100vh - 240px);
        text-align: center;
    }
    #data {
        padding: 5px 0px;
        height: 25px;
    }
    #headertable {
        text-align: center;
    }
    #form {
        width: 300px;
    }

    #contentsigin {
        display: flex;
        justify-content: center;
        width: 100%; 
    }

    #headerlist{
        display: flex;
        justify-content:space-between;
        align-items: center;
    }
    #table {
        display: flex;
        justify-content: center;
    }
    </style>
</header>
<body>
    <div id="header" >
        <h2>Monstar Lab 2021</h2>
        <p>laravel basic 2</p>
    </div>
    <div >
        @yield('content')
    </div>
</body>

resources/views/user/create.blade.php
@extends('home')
@section('content')
    <div >
        <div id= "contentsigin">
            <div id = "form">
                <form action ="{{ route('users.store')}}" method ='post' class = 'text-center'>
                @csrf
                    <div class = 'form-group'>
                        <h1>Đăng ký tài khoản</h1>
                    </div>
                    <div class = "form-group {{$errors->has('mail_address') ? 'has-error' : ''}} ">
                        <lable for = 'mail_address' class="control-label" >địa chỉ email</lable><br/>
                        <input type = 'text' name = 'mail_address' id = 'mail_address' class="form-control" value="{{old('mail_address')}}">
                        @error('mail_address')
                            <div style='color:red' class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class = "form-group {{$errors->has('name') ? 'has-error' : ''}} "> 
                        <lable for = 'name' class="control-label">tên</lable><br/>
                        <input type = 'text' name = 'name' id = 'name' class="form-control" value="{{ old('name') }}">
                        @error('name')
                            <div style='color:red' class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class = "form-group {{$errors->has('password') ? 'has-error' : ''}} ">
                        <lable for='password' class="control-label">mật khẩu</lable><br/>
                        <input type = 'password' name = 'password' id = 'password' class="form-control" value="{{ old('password') }}">
                        @error('password')
                            <div style='color:red' class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>  
                    <div class = "form-group {{$errors->has('password_confirmation') ? 'has-error' : ''}} ">
                        <lable for = 'password_confirmation'class="control-label">nhập lại mât khẩu</lable><br/>
                        <input type = 'password' name = 'password_confirmation' id = 'password_confirmation' class="form-control" value="{{ old('password_confirmation') }}">
                        @error('password_confirm')
                            <div style='color:red' class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class = "form-group {{$errors->has('address') ? 'has-error' : ''}} ">
                        <lable for = 'address' class="control-label">địa chỉ</lable><br/>
                        <input type = 'text' name = 'address' id = 'address' class="form-control" value="{{ old('address') }}">
                        @error('address')
                            <div style='color:red' class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class = "form-group {{$errors->has('phone') ? 'has-error' : ''}} ">
                        <lable for = 'phone' class="control-label">số điện thoại</lable><br/>
                        <input type = 'number' name = 'phone' id = 'phone' class="form-control" value="{{ old('phone') }}">
                        @error('phone')
                            <div style='color:red' class="alert alert-danger">{{ $message }}</div>
                        @enderror
                    </div>
                    <div class = "form-group">
                        <button type = 'submit' name = 'submit' class = 'btn btn-primary'>Tạo tài khoản</button> 
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/listusers.blade.php
@extends('home')
@section('content')
    <div id ="content"> 
        <div id ="headerlist">
            <div>
                <div>
                    <h1>DANH SÁCH NGƯỜI DÙNG</h1>
                </div>
                <div style='color:green'>
                    @if(session()->has('message'))
                        <div>{{session('message')}}</div>
                    @endif
                </div>
            </div> 
            <div>
                <form action ="{{ route('users.create')}}" method ='get'>
                    <div>
                        <button type = 'submit' name = 'submit' class = 'btn btn-primary'>TẠO TÀI KHOẢN</button> 
                    </div>
                </form>
            </div>
        </div>
        <div id="table" > 
            <table>
                <thead>
                    <tr>
                        <th id = "headertable">STT</th>
                        <th id = "headertable">Địa chỉ email</th>
                        <th id = "headertable">Tên</th>
                        <th id = "headertable">Địa chỉ</th>
                        <th id = "headertable">Số điện thoại</th>
                    </tr>
                </thead>
                <tbody>
                    @php 
                        $serial = ($data->currentPage()-1)*($data->perPage());
                    @endphp
                    @foreach ($data as $key => $dt)
                        <tr id ="data">
                            <td>{{$serial + $key + 1}}</td>
                            <td>{{$dt->mail_address}}</td>
                            <td>{{$dt->name}}</td>
                            <td>{{$dt->address}}</td>
                            <td>{{$dt->phone}}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        <div >
            <spam>
                {{ $data->links() }}
            </spam>
        </div>
    </div>
@endsection